site_name: All Things Cloud Native
site_author: All Things Cloud Native
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

# Repository
# Repository
repo_name: allthingscloudnative
repo_url: https://github.com/ams0/allthingscloudnative.git
edit_uri: edit/master/docs

# Navigation
nav:
  - Welcome:
    - About the workshop: index.md
  - Docker:
    - Lab 1: lab1.md
    - Lab 2: lab2.md
  - Kubernetes:
    - Getting started: kubernetes/index.md
  - Observability:
    - Getting started: observability/index.md
  - Security:
    - Getting started: security/index.md
  - Azure Kubernetes:
    - Getting started: aks/index.md
  - Openshift:
    - Getting started: openshift/index.md
  - References:
    - Additional resources: references/RESOURCES.md
    - Contributors: references/CONTRIBUTORS.md

# Copyright
copyright: Copyright &copy; 2023 Lovelace Engineering B.V.

# Theme
theme:
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: material/library
  features:
    - navigation.tabs
    #- navigation.instant

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ams0
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lovelaceeng
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/lovelace-engineering/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/cloudnativeams
    - icon: fontawesome/brands/dev
      link: https://dev.to/ams0

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde